blank_issues_enabled: false
contact_links:
  - name: 💬 Discussões gerais
    url: https://github.com/qway-tech/qa2ts-brasil/discussions
    about: Perguntas abertas e conversas que não se encaixam em uma issue específica
